_target_: gem.method.torch.TorchTabularTrainer
model_type: ft_transformer
use_gpu: true
epochs: 50
batch_size: 512
lr: 0.001
weight_decay: 0.0
patience: 10
model_params:
  d_token: 64
  n_heads: 4
  n_layers: 3
  dropout: 0.1
  activation: relu
  use_cls_token: true
