_target_: gem.method.torch.TorchTabularTrainer
model_type: mlp
use_gpu: true
epochs: 50
batch_size: 1024
lr: 0.001
weight_decay: 0.0
patience: 10
model_params:
  hidden_sizes: [256, 128]
  dropout: 0.1
  activation: relu
