defaults:
  - model: elasticnet
  - train_config: sklearn
  - trainer: sklearn
  - evaluator: regression
  - importance_extractor: sklearn
  - transform_pipeline: defaults
  - _self_

name: elasticnet
