defaults:
  - model: torch_ft
  - train_config: torch_ft
  - experiment_config: torch
  - trainer: torch_ft
  - evaluator: regression
  - importance_extractor: torch
  - transform_pipeline: defaults
  - _self_
