defaults:
  - model: lgbm
  - train_config: lgbm
  - experiment_config: lgbm
  - trainer: lgbm
  - evaluator: lgbm
  - importance_extractor: lgbm
  - tuner: lgbm
  - adapter: lgbm
  - transform_pipeline: defaults
  - _self_