defaults:
  - model: torch_mlp
  - train_config: torch_mlp
  - experiment_config: torch
  - trainer: torch_mlp
  - evaluator: regression
  - importance_extractor: torch
  - transform_pipeline: defaults
  - _self_
