defaults:
  - model: xgb
  - train_config: gbdt
  - trainer: xgb
  - evaluator: regression
  - importance_extractor: xgb
  - tuner: xgb
  - adapter: xgb
  - transform_pipeline: defaults
  - _self_

name: xgb

train_config:
  num_boost_round: 200
  early_stopping_rounds: 50
  feval_names: ["rmse"]
  objective_name: "regression"
  verbose_eval: 1
