_target_: gem.data.SourceSpec
name: bench3
format: feather
# path: C:/Users/123/data/feather/benchmark/bench3_20250822.fea
layout: wide
pivot: from_date
date_col: date
code_col: code
value_col: bench3_value
path: /project/model_share/fac_hy/score_file/sub_score/label1/bench3_20250822.fea
