_target_: gem.method.base.base_transform.BaseTransformPipeline
transforms:
  - _target_: gem.method.base.base_transform.FillNaNTransform
    value: 0.0
    method: constant
  - _target_: gem.method.base.base_transform.WinsorizeTransform
    target: X
    lower: 0.01
    upper: 0.99
    per_date: true
  - _target_: gem.method.base.base_transform.StandardizeTransform
    target: X
    eps: 1e-8
    per_date: true
