_target_: gem.data.SourceSpec
name: bench1
format: feather
path: C:/Users/123/data/feather/benchmark/bench1_20250822.fea
# path: /project/model_share/fac_hy/score_file/sub_score/label1/bench1_20250822.fea
