_target_: gem.data.SourceSpec
name: bench4
format: feather
path: C:/Users/123/data/feather/benchmark/bench4_20250822.fea
# path: /project/model_share/fac_hy/score_file/sub_score/label1/bench4_20250822.fea