_target_: gem.data.SourceSpec
name: bench5
format: feather
path: C:/Users/123/data/feather/benchmark/bench5_label1.fea
layout: wide
pivot: from_date
date_col: date
code_col: code
value_col: bench5_value
# path: /project/model_share/fac_hy/score_file/bench5_label1.fea
