_target_: gem.data.SourceSpec
name: bench2
format: feather
path: C:/Users/123/data/feather/benchmark/bench2_20250822.fea
# path: /project/model_share/fac_hy/score_file/sub_score/label1/bench2_20250822.fea