_target_: gem.data.SourceSpec
name: liquidity
format: feather
path: C:/Users/123/data/feather/liquidity/can_trade_amt1.fea
layout: wide
pivot: from_index
index_col: index
date_col: date
code_col: code
value_col: liquidity_value
# path: /project/model_share/fac_hy/share_1/label_data/can_trade_amt1.fea
