_target_: gem.data.SourceSpec
name: ret_raw
format: feather
path: C:/Users/123/data/feather/ret/label1.fea
layout: wide
pivot: from_index
index_col: index
date_col: date
code_col: code
value_col: ret_raw_value
# path: /project/model_share/fac_hy/share_1/label_data/label1.fea
