_target_: gem.data.SourceSpec
name: score
format: feather
path: C:/Users/123/data/feather/score/label_1_benchmark_20250619.fea
layout: wide
pivot: from_date
date_col: date
code_col: code
value_col: score_value
# path: /project/model_share/fac_hy/score_file/label_1_benchmark_20250619.fea
