# Bayesian training configuration
_target_: gem.method.training_dataclasses.TrainConfig

# Training parameters
params:
  model_type: "bayesian_ridge"
  alpha_1: 1.e-6
  alpha_2: 1.e-6
  lambda_1: 1.e-6
  lambda_2: 1.e-6
  n_iter: 300
  tol: 1.e-3

num_boost_round: 1
early_stopping_rounds: 1
feval_names: ["pearsonr_ic"]
objective_name: "regression"
seed: 42
verbose_eval: 1
