_target_: gem.experiment.ExperimentConfig
name: sklearn
output_dir: ${hydra:runtime.output_dir}
state_policy:
  _target_: gem.experiment.StatePolicyConfig
  mode: per_split
n_trials: 0
parallel_trials: 1
use_ray_tune: null
seed: 42
ray_address: null
num_cpus: null
num_gpus: null
use_ray: false
resource_request:
  trial_gpus: 0
  final_train_gpus: 0
  trial_cpus: 4
  final_train_cpus: 4
visualization:
  enabled: false
  export_csv: true
  heatmap: true
  animation: true
  distribution: true
  show: false
  interval: 800
  output_subdir: plots
