# Bayesian model configuration
_target_: sklearn.linear_model.BayesianRidge

# Basic model parameters
alpha_1: 1.e-6
alpha_2: 1.e-6
lambda_1: 1.e-6
lambda_2: 1.e-6
n_iter: 300
tol: 1.e-3
compute_score: true
